### ISSUE TITLE
I need Help with coding

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/components-on-a-grid#2]
@thatkidmadrid 
Hey Christian, I've been having a hard time with understanding coding and this assignment. I've gone for extra help in lab. I'm still having a hard time understanding. what options do I have for extra help. and for this assignment i'm not sure why my spacings between my figures are off.

**Comment by thatkidmadrid** [comment]
Hey Emma, I will reach out to the program heads regarding tutors. I'll take a look at your repo shortly and see if I can lead you in a good direction

**Comment by thatkidmadrid** [comment]
You're so close!
To achieve the correct spacing: I think a big hint is using the `gap` property for the grid to do the spacing instead of the margins and padding that you used on different components. I played around and this is messing up some other positioning, which should be quick fixes when you give that a shot.
Also, don't overthink the positioning of the nav items. Using flex is right to get the items to align horizontally, but the extra property you're using to justify them may be too complex. Perhaps a simple padding on the links will get you the spacing you're looking for

Anyways, don't get discouraged, you're very close!

Hope this helps,
Christian

**Comment by EmmaJLussier** [comment]
Hey sorry Christian I tried to figure out gap values last night. I'm just a little confused how I should apply them to the grid or what value to but inside the website says 1rem is there other values you used?

**Comment by thatkidmadrid** [comment]
Hey Emma, the gap is 1rem; the margins and paddings for other components that you added because you didn't use the grid gap property will throw off the spacing if you add the gap.

**Comment by thatkidmadrid** [comment]
Another big hint is using padding on an element that surrounds everything to achieve the spacing around the items that the grid gap doesn't create

**Comment by EmmaJLussier** [comment]
Hey Christian I'm like 1% off do you mind giving me one more hint I'm thinking the nav is off or the paragraphs?

**Comment by thatkidmadrid** [comment]
Something that's sticking out to me is to take a look at how you're justifying the flex contents of the nav. Like I said before I think you may be over complicating what's going on in there. maybe just having padding around the links to make them easier to click will get the spacing you're looking for

**Comment by EmmaJLussier** [comment]
Ok so I put padding on the links it did work but the nav is still off center where it is supposed to be.

**Comment by EmmaJLussier** [comment]
Thank you I got it submitted :)

**Comment by EmmaJLussier** [comment]
Sorry I think i remember you saying we have to record ourselves reading the css right?

**Comment by thatkidmadrid** [comment]
Hey Emma, that's right

In the bottom section of the activity outline it says to record yourself reading the final contents of your css and I will listen and provide feedback. Attach the recording to an issue and tag me :)
